filters/urls.py
from django.urls import path
from . import views

app_name = 'shoes'
urlpatterns = [
    path('', views.index, name="index"),
    path('brand/<brand_id>', views.brand_details, name="brand_details"),
    path('group/<group_id>', views.group_details, name="group_details"),
    path('type/<type_id>', views.type_details, name="type_details")
]

shoes/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.home),
    path('admin/', admin.site.urls),
    path('homepage/', include('filters.urls'))
]

filters/models.py
from django.db import models
from django.utils import timezone

# Create your models here.


class AgeGroup(models.Model):
    name = models.CharField(max_length=255)
    logo = models.CharField(max_length=10000)

    def __str__(self):
        return self.name


class ShoeType(models.Model):
    name = models.CharField(max_length=255)
    logo = models.CharField(max_length=10000)

    def __str__(self):
        return self.name


class Brand(models.Model):
    name = models.CharField(max_length=255)
    logo = models.CharField(max_length=10000)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=255)
    shoe_size = models.CharField(max_length=15)
    img1_url = models.CharField(max_length=10000)
    img2_url = models.CharField(max_length=10000)
    img3_url = models.CharField(max_length=10000)
    img4_url = models.CharField(max_length=10000)
    age_group = models.ForeignKey(AgeGroup, on_delete=models.CASCADE)
    shoe_type = models.ForeignKey(ShoeType, on_delete=models.CASCADE)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    time_created = models.DateTimeField(default=timezone.now)

filters/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Product, Brand, AgeGroup, ShoeType
# Create your views here.


def index(request):
    brand = Brand.objects.all()
    products = Product.objects.all()
    for_user = AgeGroup.objects.all()
    shoe_type = ShoeType.objects.all()
    return render(request, 'shoes/index.html', {'products': products, 'brand': brand, 'for_user': for_user, 'shoe_type': shoe_type})


def brand_details(request, brand_id):
    brand_logo = Brand.objects.get(id=brand_id)
    product = Product.objects.filter(brand_id=brand_id)
    return render(request, 'shoes/details.html', {'prod': product, "item": brand_logo})


def group_details(request, group_id):
    user_group = AgeGroup.objects.get(id=group_id)
    product = Product.objects.filter(age_group_id=group_id)
    return render(request, 'shoes/details.html', {'prod': product, "item": user_group})


def type_details(request, type_id):
    shoe_type = ShoeType.objects.get(id=type_id)
    product = Product.objects.filter(shoe_type_id=type_id)
    return render(request, 'shoes/details.html', {'prod': product, "item": shoe_type})

shoes/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'home.html')

filters/templates/shoes/details.html
{% extends 'base.html' %}
{% block content %}
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
    <img src="{{item.logo}}" height="100" alt="">&nbsp &nbsp{{item.name}}
  </a>
</nav>
<div class="card-columns" >
{% for product in prod %}
<div class="card" style="width: 18rem;">
  <img src="{{product.img1_url}}" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">{{product.brand}}</h5>
    <p class="card-text">{{product.name}}</p>
    </div>
</div>
{% endfor %}
</div>

{% endblock  %}

filters/templates/shoes/index.html
{% extends 'base.html' %}

{% block nav %}

<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
        aria-haspopup="true" aria-expanded="false">
        Brand
    </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        {% for b in brand %}
        <a class="dropdown-item" href="{% url 'shoes:brand_details' b.id %}"><img src="{{b.logo}}" height="70"></img>
            &nbsp
            &nbsp &nbsp {{b.name}} </a>
        {% endfor %}
    </div>
</li>
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
        aria-haspopup="true" aria-expanded="false">
        For
    </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        {% for user in for_user %}
        <a class="dropdown-item" href="{% url 'shoes:group_details' user.id %}"><img src="{{user.logo}}"
                height="100"></img>
            &nbsp
            &nbsp &nbsp {{user.name}} </a>
        {% endfor %}
    </div>
</li>
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
        aria-haspopup="true" aria-expanded="false">
        Shoe Type
    </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        {% for st in shoe_type %}
        <a class="dropdown-item" href="{% url 'shoes:type_details' st.id %}">{{st.name}}</a>
        {% endfor %}
    </div>
</li>

{% endblock  %}


{% block content %}
<nav class="navbar navbar-dark bg-dark">
    <span class="navbar-brand mb-0 h1">Shoes for everyone</span>
</nav>
<div class="bg-image img1">
    <a href="{% url 'shoes:group_details' 1 %}">
        <div class="bg-text">Mens</div>
    </a>
</div>
<div class="bg-image img2">
    <a href="{% url 'shoes:group_details' 2 %}">
        <div class="bg-text">Womens</div>
    </a>
</div>
<div class="bg-image img3">
    <a href="{% url 'shoes:group_details' 5 %}">
        <div class="bg-text">kids</div>
    </a>
</div>

{% endblock %}

templates/home.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body, html {
  height: 100%;
  margin: 0;
  font-family: Arial, Helvetica, sans-serif;
}

* {
  box-sizing: border-box;
}

.bg-image {
  /* The image used */
  background-image: url("https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRXPuWSZuSlGJt-a8FNqlohsxeOGk13Eg0fogpk9JcGJGzl_b5vYA");
  
  /* Add the blur effect */
  filter: blur(8px);
  -webkit-filter: blur(8px);
  
  /* Full height */
  height: 100%; 
  
  /* Center and scale the image nicely */
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;
}

/* Position text in the middle of the page/image */
.bg-text {
  background-color: rgb(0,0,0); /* Fallback color */
  background-color: rgba(0,0,0, 0.4); /* Black w/opacity/see-through */
  color: white;
  font-weight: bold;
  border: 3px solid #f1f1f1;
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  z-index: 2;
  width: 30%;
  padding: 1px;
  text-align: center;
}
</style>
</head>
<body>

<div class="bg-image"></div>

<a href="{% url 'shoes:index' %}">
    <div class="bg-text">
        <h1 style="font-size:50px">Click to shop</h1>
    </div>
</a>

</body>
</html>